# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: doc
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install binary dependencies
      run: |
        sudo apt-get update && sudo apt-get install libopenmpi-dev openmpi-common openmpi-bin libvtk6-dev
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest matplotlib
        python -m pip install sphinxcontrib.bibtex sphinx_drove_theme sphinx-autodoc-typehints sphinx-automodapi # for docs
        python -m pip install -e .[extra]
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: compiling LIGGGHTS
      run: |
        python setup.py build_liggghts
    - name: Install pygran
      run: |
        python -m pip install .
    - name: Generate sphinx docs
      run: |
        cd docs/sphinx
        bash clean.sh
        bash build.sh

    - name: Commit documentation changes
      shell: bash -l {0}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # the return code.

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.ref }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
